### ISSUE TITLE
Icon not rendered

### ISSUE THREAD

**Issue by SalvatoreDiFede** [Redth/Maui.ContentButton#2]
Hi Jonathan. 
Thanks for working at this usefull contentbutton easy solution.
Got issue with icons: any idea on why arent displayed when inserted in contentbutton?

Actually testing with these:
https://github.com/AathifMahir/MauiIcons (AathifMahir.Maui.MauiIcons.FontAwesome.Solid)

Need any info or scenario to replicate?

Thanks again
Salvo

**Comment by Redth** [comment]
Not sure, but it could be something in that control that's not working.  I tested here and I see the same as you, but if I just use a `FontImageSource` with the same font from their project and use the glyph etc manually it is working fine inside the content button.

It could also be that the visual tree isn't seeing the nested content items properly still, so I'll have a look at that yet too.

**Comment by Redth** [comment]
Ahh yep, that was it, I was using the incorrect methods to manage the inner content on the visual tree.  Presumably that library needs some lifecycle events/methods (maybe Loaded) called that weren't getting called.

It works after this change: https://github.com/Redth/Maui.ContentButton/commit/86fd2d6169af55ef94415a4df59ee344a875335c

Will be merging that PR soon and pushing another package.

**Comment by SalvatoreDiFede** [comment]
I could love you ❤️
Thanks!
